kind: pipeline
type: docker
name: default

steps:
- name: test
  image: node
  commands:
  - npm install
  - npm run lint

- name: build
  image: node
  commands:
  - npm run build
  - echo build pyz app

- name: greeting
  image: alpine
  commands:
  - echo hello
  - echo world
  - pwd
  - ls -la

  - name: start
  image: node
  commands:
  - npm run start
  - echo start pyz app