kind: pipeline
type: docker
name: default

steps:
- name: test
  image: node
  commands:
  - npm ci
  - npm run lint

- name: build
  image: node
  commands:
  - npm run build
  - echo build pyz app

- name: greeting
  image: alpine
  commands:
  - echo world 
  - pwd
  - ls -la

- name: secret
  image: alpine
  environment:
    USERNAME: 
      from_secret: user_name
    USERNAMETWO: David
  commands:
  - echo hola $USERNAME
  - echo Hola $USERNAMETWO

# - name: start
#   image: node
#   commands:
#   - npm run start