kind: pipeline
type: docker
name: default

steps:
- name: test
  image: node
  commands:
  - npm install
  - npm run lint
  - npm test

- name: greeting
  image: alpine
  commands:
  - echo hello
  - echo world