
trigger:
- main

pool:
  name: Default

stages:
- stage: Inicio
  jobs:
    - job: Hola_mundo
      continueOnError: false
      steps:
        - task: NodeTaskRunnerInstaller@0
          displayName: 'Install node runner 6'
        - script: npm ci
          displayName: Build
          workingDirectory: $(System.DefaultWorkingDirectory)/src
